# Generated by Django 4.2.3 on 2023-07-31 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 7, 31, 6, 16, 44, 177998, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
